const app = require('./serverInit')
const user = require('./routes/user')
const test = require('./routes/test')
const document = require('./routes/document')
const edit = require('./routes/edit')
const history = require('./routes/history')
const search = require('./routes/search')
const upload = require('./routes/upload')

app.use('/user', user)
app.use('/test', test)
app.use('/document', document)
app.use('/edit', edit)
app.use('/history', history)
app.use('/search', search)
app.use('/upload', upload)

app.get('/', (req, res) => {
    // logger.info('GET /')
    res.send("Hello World !!!")
})